### DISCUSSION TITLE
[Feature Request/QA] Option to virtualize items by an even number, due to css even/odd problems

### DISCUSSION THREAD

**Discussion by OmarOmeiri** [TanStack/virtual#407] [Ideas]
If you have let's say a table that has CSS for even and odd rows, the virtualizer breaks the styles and the rows start flickering back and forth.

I have the following CSS 
```css
.TBody {
  color: #faf9f7ff;
}

.TBody > div:nth-child(even) {
  background-color: #3d4045;
}

.TBody > div:nth-child(odd) {
  background-color: #707070ff;
}
```

I've tried messing around with the `overscan` option, but without success.
I propose adding an option like 
```ts
  const rowVirtualizer = useVirtualizer({
    getScrollElement: () => tableContainerRef.current,
    count: rows.length,
    overscan: 11,
    estimateSize: () => 45,
    chunkSize:  2, // <-- HERE
  });
```
So that the virtualizer renders elements in pairs.
The current virtualizer behavior is rendering elements one by one.
Could this be done with the current set of tools?

https://user-images.githubusercontent.com/46783176/195940101-e60cfccc-feba-494c-9517-44491ac6f735.mp4

**UPDATE**

Solved by changing the CSS logic to: 
```css
.TBody {
  color: #faf9f7ff;
}

.Even {
  background-color: #3d4045;
}

.Odd {
  background-color: #707070ff;
}
```

And adding a dynamic class in the table row based on the virtualizer index:
```ts
virtualRows.map((virtualRow) => {
  const row = rows[virtualRow.index] as Row<T>;
  return (
    <TableRow
      key={row.id}
      row={row}
      className={virtualRow.index % 2 === 0 ? classes.Even : classes.Odd}
      columnOrder={columnOrder}
      styles={styles}
      highLightedRows={highlightedRows}
      setHighLightedRows={setHighLightedRows}
    />
  );
})
```
Nevertheless, this would be a nice addition.
