### ISSUE TITLE
Broken scrolling behaviour with CSS scroll-snapping on Chrome

### ISSUE THREAD

**Issue by cmmartti** [TanStack/virtual#267]
Adding CSS [scroll-snapping](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-type) to a React Virtual virtualizer prevents scrolling with the mouse wheel or trackpad in Chrome/Edge. The scrolling motion starts, but it bounces back to the starting point in a stuttering motion many times a second. Scroll-snapping works normally on Firefox.
 
https://user-images.githubusercontent.com/6448223/154786977-28e52905-7f18-4e2c-8bee-d0f12adddbd2.mp4

Here is a CodeSandbox example that demonstrates the bug, based on one from the docs:
 - [Preview](https://4nn8y5.sse.codesandbox.io/)
 - [Code](https://codesandbox.io/s/cranky-nova-4nn8y5?file=/src/index.css:56-277)
 
These are the only additions to the example:

```css
.List {
  scroll-snap-type: both mandatory;
}

.ListItemEven,
.ListItemOdd {
  scroll-snap-align: start;
}
```

Any ideas on what's causing this weird behaviour?
